#!/usr/bin/env python3

import random
import string

while True:
    try:
        get_length = input("Enter number of characters in the string. ")
        length = int(get_length)
        def gen_random_string(length):
            letters = string.ascii_letters + string.digits + string.punctuation
            result_str = ''.join(random.choice(letters) for i in range(length))
            print("Random string of length", length, "is:", result_str)
        if get_length.isdigit() == True:
            gen_random_string(length)
        else:
            exit()
    except ValueError:
        exit()
